rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
sudo: false
cache: bundler

env:
  global:
    - SKIP_INTERACTIVE=yes
  matrix:
    - IMAGE_VISE_ENABLE_FORK=no
    - IMAGE_VISE_ENABLE_FORK=yes

matrix:
  allow_failures:
    - env: IMAGE_VISE_ENABLE_FORK=yes

script: bundle exec rspec
